version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg-local:
    image: postgres:14-alpine3.17
    restart: always
    env_file:
      - "local.env"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  pg-prod:
    image: postgres:14-alpine3.17
    restart: always
    env_file:
      - "prod.env"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data
    ports:
      - "54322:5432"

  migrator-local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    env_file:
      - "local.env"
    depends_on:
      - pg-local

  migrator-prod:
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    env_file:
      - "prod.env"
    depends_on:
      - pg-prod